/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseField: typeof import('./src/components/form/BaseField.vue')['default']
    DataTableHead: typeof import('./src/components/table/DataTableHead.vue')['default']
    DataTablePagination: typeof import('./src/components/table/DataTablePagination.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    FeatureUnderDevelopment: typeof import('./src/components/common/FeatureUnderDevelopment.vue')['default']
    PageDateTopbar: typeof import('./src/components/common/PageDateTopbar.vue')['default']
    PageSurface: typeof import('./src/components/layout/PageSurface.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
